export const FETCH_ITEMS_START = 'FETCH_ITEMS_START';
export const FETCH_ITEMS_SUCCESS = 'FETCH_ITEMS_SUCCESS';
export const FETCH_ITEMS_FAIL = 'FETCH_ITEMS_FAIL';
export const RESET_ITEMS = 'RESET_ITEMS';

export const CREATE_ITEMS_START = 'CREATE_ITEMS_START';
export const CREATE_ITEMS_SUCCESS = 'CREATE_ITEMS_SUCCESS';
export const CREATE_ITEMS_FAIL = 'CREATE_ITEMS_FAIL';

export const REMOVE_ITEM_START = 'REMOVE_ITEM_START';
export const REMOVE_ITEM_SUCCESS = 'REMOVE_ITEM_SUCCESS';
export const REMOVE_ITEM_FAIL = 'REMOVE_ITEM_FAIL';

export const CREATE_TEMPLATE_START = 'CREATE_TEMPLATE_START';
export const CREATE_TEMPLATE_SUCCESS = 'CREATE_TEMPLATE_SUCCESS';
export const CREATE_TEMPLATE_FAIL = 'CREATE_TEMPLATE_FAIL';

export const FETCH_TEMPLATES_START = 'FETCH_TEMPLATES_START';
export const FETCH_TEMPLATES_SUCCESS = 'FETCH_TEMPLATES_SUCCESS';
export const FETCH_TEMPLATES_FAIL = 'FETCH_TEMPLATES_FAIL';

export const FETCH_TEMPLATE_START = 'FETCH_TEMPLATE_START';
export const FETCH_TEMPLATE_SUCCESS = 'FETCH_TEMPLATE_SUCCESS';
export const FETCH_TEMPLATE_FAIL = 'FETCH_TEMPLATE_FAIL';

export const FETCH_FOLDERS_START = 'FETCH_FOLDERS_START';
export const FETCH_FOLDERS_SUCCESS = 'FETCH_FOLDERS_SUCCESS';
export const FETCH_FOLDERS_FAIL = 'FETCH_FOLDERS_FAIL';

export const CREATE_FOLDER_START = 'CREATE_FOLDER_START';
export const CREATE_FOLDER_SUCCESS = 'CREATE_FOLDER_SUCCESS';
export const CREATE_FOLDER_FAIL = 'CREATE_FOLDER_FAIL';

export const REMOVE_FOLDER_START = 'REMOVE_FOLDER_START';
export const REMOVE_FOLDER_SUCCESS = 'REMOVE_FOLDER_SUCCESS';
export const REMOVE_FOLDER_FAIL = 'REMOVE_FOLDER_FAIL';
